[pytest]
addopts = 
    -s -ra -vv -p no:warnings -p no:sugar
    --tb=short --color=no --env=staging --debuglog

testpaths = tests

python_files = test_*.py
python_classes = Test
python_functions = test_

norecursedirs = .venv .pytest_cache __pycache__ .git .github .vscode .idea .DS_Store

markers =
    web: web tests
    iphone: iphone tests
    ipad: ipad tests
    mac: mac tests
    api: api tests