base_url:
  api: "https://v41-api.k8s.flodev.net"
  oauth2: "https://oauth2-api.k8s.flodev.net"
  sabredav: "https://dav.k8s.flodev.net"
  flodav: "https://flodav.k8s.flodev.net"
  chime: "https://chime.k8s.flodev.net"
  admin: "https://admin-api.k8s.flodev.net/intl-api"
  cdn: "https://static-cdn.flodev.net"
  storage: "https://storage.k8s.flodev.net"
  auto_util: "https://auto-util.k8s.flodev.net"
  realtime: "https://realtime.k8s.flodev.net"
  subscriptions: "https://v41-api.k8s.flodev.net"
  subscriptions_webhook: "https://flo-subscription.k8s.flodev.net"
  web_api: "https://domailsvr.k8s.flodev.net/v0.1"

web: "https://flo.k8s.flodev.net"

user: "auto763e90_quang@flodev.net"
user2: "auto763e90_quang_mem1@flodev.net"
user3: "auto763e90_quang_mem2@flodev.net"
password: "QWFAMTIzNDU="

appium:
  platformName: "iOS"
  deviceName: "iPhone Dev"
  udid: "auto"
  app: "./apps/dev.app"
